# Site
name: "PEEP DATA"
title: "PEEP DATA"
owner: "Lucas Zamora"
description: "Compartiendo conocimientos, códigos y más."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
#baseurl: '/blogs'
google_analytics: 'UA-90591413-2'
disqus: 'peepdata'
mailchimp-list: 'https://github.us7.list-manage.com/subscribe/post?u=368fc8bf7697aece620acbec6&amp;id=35374c02a5'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  lzamora:
    name: Lucas Zamora
    display_name: Lucas Z.
    gravatar: 4b13d39dec603471e5268e342533dedb
    email: lucas.e.zamora@gmail.com
    web: https://lezamora.github.io
    twitter: https://twitter.com/lucaszamora10
    description: "Entusiasta, autodidacta y con ganas de seguir aprendiendo. 
    Quiero compartiles aquellas cosas que resulten interesantes 
    y que puedan aportarles valor en el desarrollo de sus carreras."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, 'vendor']
